root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o tmp/main ."
bin = "tmp/main"
include_ext = ["go", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]

[log]
level = "debug"

[serve]
cmd = "./tmp/main"
delay = "100ms"
